version: '3.8'

services:
  aegis-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - POLICY_DIR=/app/policies
      - OTEL_ENDPOINT=jaeger:4317
    volumes:
      - ./policies:/app/policies:ro
      - ./logs:/app/logs
    depends_on:
      - jaeger
    restart: unless-stopped

  admin-ui:
    build:
      context: ./admin-ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE=http://localhost:8080
    depends_on:
      - aegis-gateway
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:1.51
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: unless-stopped

networks:
  default:
    name: aegis-network
